DROP TABLE aluno_fila_instancia CASCADE CONSTRAINTS;
DROP TABLE alunos_fila CASCADE CONSTRAINTS;
DROP TABLE filas CASCADE CONSTRAINTS;
DROP TABLE instancias CASCADE CONSTRAINTS;
DROP TABLE recursos CASCADE CONSTRAINTS;
DROP TABLE programas CASCADE CONSTRAINTS;
DROP TABLE instituicoes CASCADE CONSTRAINTS;
DROP TABLE alunos CASCADE CONSTRAINTS;

DROP SEQUENCE s_instituicao;
DROP SEQUENCE s_recurso;
DROP SEQUENCE s_programas;
DROP SEQUENCE s_instancia;
DROP SEQUENCE s_fila;
DROP SEQUENCE s_aluno;
DROP SEQUENCE s_alunos_fila;
